# Generated by Django 6.0.5 on 2026-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (desk job, no exercise)'), ('light', 'Light (1–3 days/week)'), ('moderate', 'Moderate (3–5 days/week)'), ('active', 'Active (6–7 days/week)'), ('very_active', 'Very Active (athlete / physical job)')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner (0–1 year training)'), ('intermediate', 'Intermediate (1–3 years training)')], default='beginner', max_length=20),
        ),
    ]
