# Generated by Django 6.0.5 on 2026-06-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chest',
            field=models.FloatField(blank=True, help_text='Chest circumference in cm', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hip',
            field=models.FloatField(blank=True, help_text='Hip circumference in cm', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thigh',
            field=models.FloatField(blank=True, help_text='Thigh circumference in cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='waist',
            field=models.FloatField(help_text='Waist circumference in cm', null=True),
        ),
    ]
