# Generated by Django 6.0.5 on 2026-06-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_chest_userprofile_hip_userprofile_thigh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chest',
            field=models.FloatField(help_text='Chest circumference in cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hip',
            field=models.FloatField(help_text='Hip circumference in cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thigh',
            field=models.FloatField(help_text='Thigh circumference in cm', null=True),
        ),
    ]
