# Generated by Django 6.0.5 on 2026-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='avg_bpm',
            field=models.FloatField(blank=True, help_text='Average heart rate during workout (optional)', null=True),
        ),
    ]
